In [5]:
#np.random.choice(['ala','ma','kota'], p=[0.1,0.1,0.8])

#Projekt 1
##1. Napisz program, uczący się gry “papier, kamień, nożyce”. Jako algorytm uczący zastosuj łańcuch Markowa z macierzą przejść pomiędzy trzema stanami (Papier, Kamień, Nożyce). Nauka gry polega na korekcie macierzy przejść (prawdopodobieństwa warunkowe zmiany stanu),
##2. Wartość wypłaty: 1 w przypadku wygranej, −1 w przypadku przegranej i 0 w przypadku remisu,
##3. Przeprowadź ciąg kilkudziesięciu gier “kamień, papier, nożyce”. Sporząź wykres jak zmienia się stan kasy w każdym kroku gry.

In [6]:
import numpy as np

In [16]:
matrix = np.ones((3,3))

print (matrix)

print ('This is a game of Rock, Paper, Scissors')

def rock():
    prevDec=0

def paper():
    prevDec=1

def scissors():
    prevDec=2

options = {
    "R": rock(),
    "P": paper(),
    "S": scissors()}

iter = 1
prevDec = 0
lastRound = ''
while (decision != "EXIT"):

    decision = input('this is game nr.' + iter.__str__() + ' input "r" - for Rock \n "p"- for Paper \n "s" for Scissors \n You can also stop playing The Game by inputing "exit"')

    decision=decision.capitalize()
    print(decision)

    if (lastRound in options):
        options[lastRound]()
    
    row_sums = matrix.sum(axis=1)
    
    rproc=matrix[prevDec][0] / row_sums[prevDec]
    pproc=matrix[prevDec][1] / row_sums[prevDec]
    sproc=matrix[prevDec][2] / row_sums[prevDec]
    np.random.choice(['Rock','Paper','Scissors'], p=[rproc,pproc,sproc])

    lastRound=decision
    print()





[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
This is a game of Rock, Paper, Scissors
Exit


In [22]:
import numpy as np

# create a 3x3 matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# sum all rows
row_sums = matrix.sum(axis=1)

print(matrix[1][0] )

4
